# Generated by Django 2.2.6 on 2020-02-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserv', to='user_stories.Sale'),
        ),
    ]
